In [114]:
import torch
import pandas as pd
import numpy as np 
import matplotlib.pyplot as ply
print(torch.__version__)

2.3.0


In [115]:
# !nvidia-smi //gpu info

## Introduction to Tensors

## creating tensors

In [116]:
# scalar 
scalar = torch.tensor(7)
scalar 

tensor(7)

In [117]:
scalar.ndim

0

In [118]:
# get tensor back as python number
scalar.item()

7

In [119]:
# vector 
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [120]:
vector.ndim

1

In [121]:
vector.shape

torch.Size([2])

In [122]:
# MATRIX
matrix = torch.tensor([[7,7],[8,8]])
matrix

tensor([[7, 7],
        [8, 8]])

In [123]:
matrix.ndim # no. of square brakets in end

2

In [124]:
matrix.shape

torch.Size([2, 2])

In [125]:
# TENSOR 
tensor = torch.tensor([[[1,2,3],[3,5,6],[7,8,9]]])
tensor

tensor([[[1, 2, 3],
         [3, 5, 6],
         [7, 8, 9]]])

In [126]:
tensor.ndim

3

In [127]:
tensor.shape # it means we have one 3x3 matrix

torch.Size([1, 3, 3])

In [128]:
tensor[0] # 0th dimension 

tensor([[1, 2, 3],
        [3, 5, 6],
        [7, 8, 9]])

## Random Tensors

In [129]:
# create random tensor
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6217, 0.7821, 0.1495, 0.5709],
        [0.5630, 0.6856, 0.8452, 0.4025],
        [0.0231, 0.5465, 0.7521, 0.9155]])

In [130]:
random_tensor.ndim

2

In [131]:
# create tensor similar to image tensor
image = torch.rand(size=(244,244,3)) # height x width x channel
image.shape, image.ndim

(torch.Size([244, 244, 3]), 3)

## Zeros and Ones

In [132]:
# tensor of zeros 
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [133]:
zeros * random_tensor 


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [134]:
# tensor of ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [135]:
ones.dtype

torch.float32

# Creating range of tensors and tensor-like

In [136]:
# arange(start,end,step)
one_to_ten = torch.arange(1,11,1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [137]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor data type

In [138]:
float_32_tensor = torch.tensor([3,4,5],
dtype = None,
device = None,
requires_grad = False
 )
float_32_tensor

tensor([3, 4, 5])

3 biggest errors : 
1. tensor not right shape 
2. tensor not on device 
3. tensor not right datatype

In [139]:
float_32_tensor.dtype

torch.int64

In [140]:
float_32_tensor = torch.tensor([3, 4, 5], dtype=torch.float32)
float_32_tensor.dtype

torch.float32

In [141]:
float_32_tensor = float_32_tensor.type(torch.float16)
float_32_tensor.dtype

torch.float16

# Getting information from tensors

1. tensor not right shape - tensor.shape
2. tensor not on device - tensor.device
3. tensor not right datatype - tensor.dtype

# Manipulating Tensors

In [142]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [143]:
tensor + 10 

tensor([11, 12, 13])

In [144]:
tensor * 10

tensor([10, 20, 30])

In [145]:
tensor - 10 

tensor([-9, -8, -7])

## MATRIX MULTIPLICATION 
two ways to perform multiplcation 
1. elementwise 
2. matrix multiplicaition (dot product)

In [146]:
# element wise multiplication
print(tensor, '*' , tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [147]:
# matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [148]:
%%time
value = 0
for i in range(len(tensor)): 
    value += tensor[i] * tensor[i]

CPU times: user 392 µs, sys: 330 µs, total: 722 µs
Wall time: 448 µs


In [149]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 140 µs, sys: 65 µs, total: 205 µs
Wall time: 182 µs


tensor(14)

In [150]:
%%time 
tensor @ tensor

CPU times: user 45 µs, sys: 7 µs, total: 52 µs
Wall time: 42 µs


tensor(14)

### two main rules of matrix multiplcation 
1. inner dimensions must match
2. resulting matrix has shape of outer dimensions

In [153]:
torch.rand(3,4) @ torch.rand(2,3)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x4 and 2x3)

In [155]:
torch.rand(2, 3) @ torch.rand(3, 4)

tensor([[0.8915, 0.6297, 0.4957, 0.5377],
        [1.0838, 0.8632, 0.6755, 0.5004]])

In [159]:
a = torch.rand(3, 4)
b = torch.rand(2, 4)

In [165]:
a @ b

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x4 and 2x4)

In [160]:
a.shape

torch.Size([3, 4])

In [161]:
b.shape

torch.Size([2, 4])

In [163]:
b.T.shape

torch.Size([4, 2])

In [ ]:
a @ b.T # transposed

tensor([[0.4270, 1.3296],
        [0.5432, 1.6797],
        [0.2190, 1.0703]])

# Tensor aggregation 

In [167]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [168]:
torch.min(x) , min(x)

(tensor(0), tensor(0))

In [169]:
torch.max(x), max(x)

(tensor(90), tensor(90))

In [170]:
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
torch.mean(x.type(torch.float16)), torch.mean(x.type(torch.float32))
# torch mean requires float32 

(tensor(45., dtype=torch.float16), tensor(45.))

In [173]:
torch.sum(x), sum(x)

(tensor(450), tensor(450))

# Indexes for aggregation 

In [175]:
# Find the position in tensor that has min value with argmin -> returns index of min value
x.argmin()

tensor(0)

In [176]:
x[0]

tensor(0)

In [177]:
x.argmax()

tensor(9)

In [178]:
x[9]

tensor(90)

# Reshaping , stacking , squeezing and unsqueezing 

- view - return a view of a tensor but keeps the memory of tensor same
- hstack , vstack
- squeeze - remove one dimension 
- unsqueeze - add on dimension 
- permute - return a view of input with dimensions permuted(swapped)

In [186]:
x = torch.arange(1.,10.)
x , x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [199]:
x_reshape = x.reshape(1,9)
x_reshape, x_reshape.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [188]:
x_reshape = x.reshape(9, 1)
x_reshape, x_reshape.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
# change view 
z = x.view(1,9)
z , z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [192]:
# changing z changes x 
z[:,0] = 5 
z,x 

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# stack tensors 
x_stack = torch.stack([x,x,x,x],dim=0) # hstack
x_stack

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# stack tensors
x_stack = torch.stack([x, x, x, x], dim=1) # vstack
x_stack

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
# torch.squeeze() - removes all single dimensions from target tensor 
x_reshape.shape

torch.Size([1, 9])

In [201]:
x_reshape.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [203]:
x_reshape.squeeze().shape

torch.Size([9])

In [209]:
print(f"Previous tensor: {x_reshape}")
print(f"Previous shape: {x_reshape.shape}")

print()
x_squeeze = x_reshape.squeeze()
# removes extra dimensions
print(f"New tensor: {x_squeeze}")
print(f"New shape: {x_squeeze.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [211]:
# torch.squeeze() - add a single dimension to target tensor at specific dim
print(f"Previous tensor: {x_squeeze}")
print(f"Previous shape: {x_squeeze.shape}")

print()
x_unsqueeze = x_squeeze.unsqueeze(dim=0)
# removes extra dimensions
print(f"New tensor: {x_unsqueeze}")
print(f"New shape: {x_unsqueeze.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [ ]:
# torch.permute() - rearranges dimension of a target tensor in specific order
x_original = torch.rand(size=(244,244,3)) # h w c 
print(f"Previous shape: {x_original.shape}")

# permute the original tensor to rearrange axis order
x_permute = x_original.permute(2,0,1) # shifts to 0->1 , 1->2 , 2->0
print(f"New shape: {x_permute.shape}")

# same memory just show differently

Previous shape: torch.Size([244, 244, 3])
New shape: torch.Size([3, 244, 244])


# Indexing



In [217]:
x = torch.arange(1,10).reshape(1,3,3)
x , x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [220]:
# index on first tensor 
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# index on dim = 1
x[0][0]  # x[0, 0]

tensor([1, 2, 3])

In [224]:
# index on dim = 2
x[0][0][0]  # x[0, 0, 0]

tensor(1)

In [225]:
# index on dim = 2
x[0][0][2]  # x[0, 0, 2]

tensor(3)

In [227]:
# You can use : to select all of the target dimension 

# get all values of 0th and 1st dimension but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [228]:
# get al values of the 0th dimension but only 1 index of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [229]:
# get index 0 of oth and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

## pytorch tensors and numpy

- you can interact 
- Data in numpy , want pytorch tensor -> torch.from_numpy(ndarray)
- Data in torch , want numpy tensor -> torch.Tensor.numpy()

be careful of dtype and do check them in conversion 

# Reproducibility (taking out random from random)

to reduce randomness , use random seed. (pseudo random)
random seed fixes the randomness  

In [230]:
# random but reproducable tensors

RANDOM_SEED = 42 
torch.manual_seed(RANDOM_SEED)
# matrix 1 :
random_a = torch.rand(3,4)

# have to do it again as requesting next random will not be same
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
# matrix 2 :
random_b = torch.rand(3, 4)

print(random_a == random_b)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# agnostics

In [232]:
# check GPU
torch.cuda.is_available()

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [ ]:
# put tensor and models on gpu for master tensor operations
tensor.to(device)