# NumPy (Numerical Python) 

The NumPy library contains multidimensional array data structures, such as the homogeneous, N-dimensional ndarray, and a large library of functions that operate efficiently on these data structures.

In [11]:
import numpy as np

Why use NumPy?

Python lists are excellent, general-purpose containers. They can be “heterogeneous”, meaning that they can contain elements of a variety of types, and they are quite fast when used to perform individual operations on a handful of elements.

NumPy shines when there are large quantities of “homogeneous” (same-type) data to be processed on the CPU.

For instance, if each element of the data were a number, we might visualize a “one-dimensional” array like a list.
 
A two-dimensional array would be like a table
 
A three-dimensional array would be like a set of tables, perhaps stacked as though they were printed on separate pages. In NumPy, this idea is generalized to an arbitrary number of dimensions, and so the fundamental array class is called ndarray: it represents an “N-dimensional array”.

Most NumPy arrays have some restrictions. For instance:

- All elements of the array must be of the same type of data.

- Once created, the total size of the array can’t change.

- The shape must be “rectangular”, not “jagged”; e.g., each row of a two-dimensional array must have the same number of columns.

When these conditions are met, NumPy exploits these characteristics to make the array faster, more memory efficient, and more convenient to use than less restrictive data structures.

## Array fundamentals

One way to initialize an array is using a Python sequence, such as a list.

In [12]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

we can access an individual element of this array as we would access an element in the original list: using the integer index of the element within square brackets.

In [13]:
a[2]

3

Like the original list, the array is mutable.



In [14]:
a[0] = 10 
a

array([10,  2,  3,  4,  5,  6])

Python slice notation can be used for indexing.

One major difference is that slice indexing of a list copies the elements into a new list, but slicing an array returns a view: an object that refers to the data in the original array. The original array can be mutated using the view.

In [15]:
a[2:5]

array([3, 4, 5])

In [16]:
b = a[3:]
print(b)
b[0] = 40 
print(b)

[4 5 6]
[40  5  6]


In [17]:
print(a)

[10  2  3 40  5  6]


Two- and higher-dimensional arrays can be initialized from nested Python sequences

In [20]:
a = np.array([[1, 2, 3,4], [ 5, 6,7,8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In NumPy, a dimension of an array is sometimes referred to as an “axis”. This terminology may be useful to disambiguate between the dimensionality of an array and the dimensionality of the data represented by the array. For instance, the array a could represent three points, each lying within a four-dimensional space, but a has only two “axes”.

Another difference between an array and a list of lists is that an element of the array can be accessed by specifying the index along each axis within a single set of square brackets, separated by commas. For instance, the element 8 is in row 1 and column 3:

In [21]:
a[1,3]

8

It is familiar practice in mathematics to refer to elements of a matrix by the row index first and the column index second. This happens to be true for two-dimensional arrays, but a better mental model is to think of the column index as coming last and the row index as second to last. This generalizes to arrays with any number of dimensions.

## Array attributes

The number of dimensions of an array is contained in the ndim attribute.

In [22]:
a.ndim

2

In [24]:
a.ndim == len(a.shape)

True

The shape of an array is a tuple of non-negative integers that specify the number of elements along each dimension.

In [23]:
a.shape

(3, 4)

The fixed, total number of elements in array is contained in the size attribute.

In [25]:
a.size

12

Arrays are typically “homogeneous”, meaning that they contain elements of only one “data type”. The data type is recorded in the dtype attribute.

In [26]:
a.dtype

dtype('int64')