# Basic array operations

You can add the arrays together with the plus sign.

In [12]:
import numpy as np

In [13]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [14]:
data - ones

array([0, 1])

In [15]:
data * data

array([1, 4])

In [16]:
data / data

array([1., 1.])

Basic operations are simple with NumPy. If you want to find the sum of the elements in an array, you’d use sum(). This works for 1D arrays, 2D arrays, and arrays in higher dimensions.

In [17]:
a = np.array([1, 2, 3, 4])

a.sum()

10

To add the rows or the columns in a 2D array, you would specify the axis.

In [18]:
b = np.array([[1, 1], [2, 2]])

axis = 0 → rows go DOWN

axis = 1 → columns go ACROSS

You can sum over the axis of rows with:

In [19]:
b.sum(axis=0)

array([3, 3])

In [ ]:
# [1  1]   ↓
# [2  2]   ↓
# ---------
# [3  3]

You can sum over the axis of column with:

In [20]:
b.sum(axis=1)

array([2, 4])

In [22]:
# → [1 + 1] = 2
# → [2 + 2] = 4


## The axis you specify is the axis that gets removed.

axis=0 → remove rows → result per column

axis=1 → remove columns → result per row